@extends('layouts.app')
@section('title', 'KPI Management')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">KPI Management</h1><p class="text-secondary-soft mb-0">Periode, indikator, assignment, dan realisasi KPI.</p></div><a href="{{ route('kpi.dashboard') }}" class="btn btn-outline-primary">Dashboard KPI</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if(auth()->user()->hasPermission('performance.create'))
<div class="row g-3 mb-3"><div class="col-lg-6"><div class="card-soft h-100"><div class="card-header">Buat periode KPI</div><div class="card-body"><form method="POST" action="{{ route('kpi.periods.store') }}" class="row g-2">@csrf<input name="name" class="form-control" placeholder="Nama periode" required><select name="type" class="form-select"><option value="monthly">Bulanan</option><option value="quarterly">Kuartal</option><option value="semester">Semester</option><option value="annual">Tahunan</option></select><input name="start_date" type="date" class="form-control" required><input name="end_date" type="date" class="form-control" required><button class="btn btn-primary">Simpan periode</button></form></div></div></div><div class="col-lg-6"><div class="card-soft h-100"><div class="card-header">Tambah indikator</div><div class="card-body"><form method="POST" action="{{ route('kpi.indicators.store') }}" class="row g-2">@csrf<input name="name" class="form-control" placeholder="Nama indikator" required><select name="perspective" class="form-select"><option value="FIN">FIN - Keuangan</option><option value="CUS">CUS - Nasabah</option><option value="IBP">IBP - Proses Internal</option><option value="LGR">LGR - Pembelajaran</option><option value="SHR">SHR - Nilai Syariah</option></select><input name="description" class="form-control" placeholder="Deskripsi / formula"><button class="btn btn-primary">Simpan indikator</button></form></div></div></div></div>
<div class="card-soft mb-3"><div class="card-header">Assign KPI ke employee</div><div class="card-body"><form method="POST" action="{{ route('kpi.assignments.store') }}" class="row g-2">@csrf<select name="performance_period_id" class="form-select" required>@foreach($periods as $item)<option value="{{ $item->id }}" @selected($period?->id === $item->id)>{{ $item->name }}</option>@endforeach</select><select name="employee_id" class="form-select" required>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_number }} - {{ $employee->first_name }} {{ $employee->last_name }}</option>@endforeach</select><select name="kpi_id" class="form-select" required>@foreach($kpis as $kpi)<option value="{{ $kpi->id }}">{{ $kpi->name }}</option>@endforeach</select><input name="target" type="number" step="0.01" min="0" class="form-control" placeholder="Target" required><input name="weight" type="number" step="0.01" min="0" max="100" class="form-control" placeholder="Bobot %" required><button class="btn btn-primary">Assign KPI</button></form></div></div>
@endif
<div class="card-soft"><div class="card-header d-flex justify-content-between align-items-center"><span>Assignment KPI</span><form method="GET" class="d-flex gap-2"><select name="period_id" class="form-select form-select-sm" onchange="this.form.submit()">@foreach($periods as $item)<option value="{{ $item->id }}" @selected($period?->id === $item->id)>{{ $item->name }}</option>@endforeach</select></form></div><div class="table-responsive"><table class="table table-soft"><thead><tr><th>Employee</th><th>Indikator</th><th>Target</th><th>Bobot</th><th>Actual</th><th>Score</th><th>Aksi</th></tr></thead><tbody>@forelse($assignments as $item)<tr><td>{{ $item->first_name }} {{ $item->last_name }}</td><td>{{ $item->kpi_name }}<div class="small text-muted">{{ $item->kpi_description }}</div></td><td>{{ $item->target }}</td><td>{{ $item->weight }}%</td><td><form method="POST" action="{{ route('kpi.actual.update',$item->id) }}" class="d-flex gap-1">@csrf @method('PATCH')<input name="actual" value="{{ $item->actual }}" type="number" step="0.01" min="0" class="form-control form-control-sm" placeholder="Actual"><button class="btn btn-sm btn-outline-primary">Simpan</button></form></td><td>{{ number_format($item->score ?? 0, 2) }}</td><td><span class="badge-soft bg-light text-secondary">{{ $item->employee_number }}</span></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada assignment pada periode ini.</td></tr>@endforelse</tbody></table></div>{{ method_exists($assignments, 'links') ? $assignments->links() : '' }}</div>
@endsection
